version: '3.8'
services:
  myapp:
    image: mmpreprodacr.azurecr.io/my-app:latest
    ports:
      - "80:80"
      - "443:443"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
#     secrets:
#   acr_credentials:
#     external: true

# secrets:
#   acr_login_server:
#     external: true
