version: '3.8'

# services:
#   myapp:
#     image: WebApp
#     ports:
#       - "80:80"
#       - "443:443"  
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Production
services:
 todoapi:
 image: todoapi
 build:
 context: ./WebApplication_1
 dockerfile: Dockerfile
#     secrets:
#   acr_credentials:
#     external: true

# secrets:
#   acr_login_server:
#     external: true
