name: Publish

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    
jobs:
  publish:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.300'
        
      - name: Restore
        run: dotnet restore ./WebApplication_1.sln
      
      - name: Build 
        run: dotnet build ./WebApplication_1.sln --configuration Release --no-restore
         
      - name: Publish
        run: dotnet publish ./WebApplication_1.sln --configuration Release --no-build
        
